apiVersion: apps/v1
kind: Deployment
metadata:
  name: yiiiiy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yiiiiy
  template:
    metadata:
      labels:
        app: yiiiiy
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: yiiiiy
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "e68fd07d-f541-4964-9c40-0ecf2972c87a"
        - name: Vless_Path
          value: "/vl555"
        - name: Vmess_UUID
          value: "e68fd07d-f541-4964-9c40-0ecf2972c87a"
        - name: Vmess_Path
          value: "/vm666"
        - name: Share_Path
          value: "/v2link"
